PNUops/ops-mvp-front

src/apis/apiClient.ts

axios interceptor Authorization 헤더 설정
Api 요청 시 Authorization 헤더에 JWT 토큰을 전달하기 위한 axios request interceptor 설정
- /apis/apiClient.ts
- request interceptor를 설정하여 token이 존재하는 경우 Authorization헤더에 주입
- token은 zustand 저장소인 useTokenStore에서 획득

feat: axios interceptor Authorization 헤더 설정

---

package-lock.json
package.json
src/apis/main.ts
src/mocks/data/sign-in.ts
src/mocks/data/teams.ts
src/pages/main/LeaderMessage.tsx
src/pages/main/TeamCard.tsx
src/pages/main/TotalCards.tsx

메인페이지 내의 api 연동 mock 테스트
- 팀 전체보기 : /teams api 로직 구현
- 카드의 썸네일 들고오기 : teamId로 썸네일 조회 api 적용 (지금은 mock로) / 썸네일 값 없을 때는 기본 카드뷰
- 팀장 수정 메시지 출력 : /teams/submission-state api 적용 테스트 및 판단 로직 구현 
- 카드 클릭 시 뷰어 페이지 이동 : navigation 사용 & UI 효과 추가 (teams/${teamId}로 해야하지만 지금은 /views로 이동)
- 메인페이지에서 뷰어 페이지로 이동할 때 hover & 마우스 포인터 효과 추가
- (궁금한점) apis/ 의 ts 파일의 기준이 궁금합니다. 팀 전체보기와 팀장 메시지 출력 api가 메인 페이지에서 사용되어서 두 개를 `main.ts`라는 하나의 파일 안에 선언해 놨습니다. 'apis의 파일 단위 == page 단위' 여도 되는지 여쭙습니다
이건 전체 화면 버전 
이건 1/2 화면 버전

feat: 메인페이지 api 연동 로직 구현 

---

.gitignore
src/apis/admin.ts
src/apis/apiClient.ts
src/main.tsx
src/mocks/data/dashboard.ts
src/mocks/data/teamslike.ts
src/mocks/data/voterate.ts
src/mocks/handlers/admin.ts
src/mocks/handlers/index.ts
src/pages/admin/AdminPage.tsx
src/pages/admin/ProjectSubmissionTable.tsx
src/pages/admin/VoteRate.tsx

관리자 페이지 api 연결
관리자 페이지 api 연결
1. apis/admin.ts -> apiClient 사용해 관리자 api 생성
2. mocks/data/dashboard, teamslike, voterate.ts -> response 타입 이름 변경
3. handlers/admin.ts 추가
4. pages/admin/Adminpage.tsx -> useQuery로 api 연결
pages/admin/VoteRate.tsx -> useQuery로 api 연결
pages/admin/ProjectSubmissionTable -> respponse 타입 이름 변경

feat: 관리자 페이지 api 연결

---

src/apis/teams.ts
src/pages/main/LeaderSection.tsx
src/pages/main/LoadingSpinner.tsx
src/pages/main/Notice.tsx
src/pages/main/TeamCard.tsx
src/pages/main/TotalCards.tsx
src/types/DTO/teams/submissionStatusDto.ts
src/types/DTO/teams/teamListDto.ts

코드리뷰 토대로 메인페이지 코드 리팩토링 및 style 약간 수정
메인페이지 api 연동 PR 코드리뷰 토대로 리팩토링
- DTO/teams 디렉토리에 Dto 파일 추가
- LeaderSection 컴포넌트 분리 : 팀장 메시지 + 에디터 버튼
- 메인페이지 로딩 시 로딩스피너 추가 
- TeamCard와 내부 요소 반응형으로 크기 변경

refactor: 메인페이지 코드리뷰 기반 리팩토링 및 스타일 수정 

---

src/layout/Header.tsx
src/pages/admin/AdminPage.tsx
src/pages/admin/ProjectSubmissionTable.tsx
src/pages/project-viewer/CommentSection/CommentFormSection.tsx

댓글 낙관적 업데이트로 수정, 헤더 admin 계정일때만 관리자페이지 노출
댓글 낙관적 업데이트로 수정, 헤더 admin 계정일때만 관리자페이지 노출
Header : admin계정만 관리자 버튼 노출, isAdmin으로 관리자 체크, /monitor -> /admin으로 수정
AdminPage / ProjectSubmissionTable : 저번 머지 때 없어진 부분 다시 넣음, unique key 에러 해결
+) 관리자 권한 없는데 url로 /admin 으로 접근시 권한없는 div 노출
CommentFormSection : Optimistic Update로 등록된 댓글 바로 보이게끔 
* onMutate : mutaionFn 실행 전 실행되는 부분 -> getQueryData로 전 댓글리스트
* onError : 실패하면 다시 전 댓글리스트로 돌려놓음
* onSettled : 성공,실패에 상관없이 실행

Fix: 댓글 낙관적 업데이트로 수정, 헤더 admin 계정일때만 관리자페이지 노출

---

src/layout/Header.tsx

Header 관리자 페이지 이동 버튼 Link로 교체
Header 관리자 페이지 이동 버튼 Link로 교체
Header div onClick={} 에서 Link to로 교체
+) 이미 /admin일때 div로 클릭 안되게끔

hotfix: Header 관리자 페이지 이동 버튼 Link로 교체

---

src/pages/main/MainPage.tsx
src/pages/main/TotalCards.tsx
src/pages/project-viewer/LikeSection.tsx

fix: 로그인, 로그아웃, 좋아요 시 메인 페이지 refetch되도록 querykey 수정
로그인, 로그아웃, 좋아요 시 메인 페이지에서 불러오는 프로젝트 전체 목록 조회 요청을 재시도할 수 있도록 queryKey 변경
- TotalCards에서 queryKey 변경
- LikeSection에서 invalidate query

fix: 로그인, 로그아웃, 좋아요 시 메인 페이지 refetch되도록 querykey 수정

---

src/pages/main/LeaderMessage.tsx
src/pages/main/LeaderSection.tsx
src/pages/main/TotalCards.tsx

팀장용 메세지 디자인 수정
UI 일관성을 위한 팀장용 메세지 디자인 수정
- LeaderSection, LeaderMessage 디자인 수정

design: 팀장용 메세지 디자인 수정

---

src/pages/project-viewer/CommentSection/Comment.tsx
src/pages/project-viewer/CommentSection/CommentFormSection.tsx
src/pages/project-viewer/CommentSection/CommentListSection.tsx
src/pages/project-viewer/CommentSection/ConfirmModal.tsx

- toast 메시지를 띄웁니다.
- 댓글 등록/편집/삭제 시
- 기존 댓글 편집/삭제 토글 메뉴를 없애고, 아이콘을 두었습니다.
- 삭제 시 모달창을 띄워 실수로 삭제하는 일이 없도록 하였습니다.
- 편집된 글과 기존 글이 같을 경우 편집되지 않도록 하였습니다.
- 255자의 글자 수 제한을 두었습니다.
- 댓글 등록창, 댓글 편집창에 적용하였습니다.
- 우측 하단에서 현재 입력된 글자 수를 확인할 수 있습니다.
- 글자 수가 200자에 도달하면 빨간색으로 표시됩니다.
- 255자를 넘으면 타이핑할 수 없습니다.
https://github.com/user-attachments/assets/8ac8b22b-0973-4b2a-87f6-0fbe0677a1f4

feat: comment section UI improvements

---

src/pages/find/FindPage.tsx

아이디 찾기 페이지 타이틀 변경
아이디 찾기 페이지의 타이틀을 적절한 제목으로 변경
- FindPage.tsx: ID/PW 찾기 => ID 찾기 / 비밀번호 변경

design: 아이디 찾기 페이지 타이틀 변경

---

src/pages/project-viewer/CarouselSection.tsx
src/pages/project-viewer/ProjectViewerPage.tsx

- carousel 이미지의 크기를 breakpoint 별로 설정하였습니다.
- 사유: 기존 뷰포트 기준 carousel 이미지의 경우, `ctrl` + `-` 화면 축소 시 이미지 크기가 변하지 않아 부자연스러움

style: carousel image reactive UI

---

src/components/RoundedButton.tsx
src/components/Spinner.tsx
src/pages/find/FindEmailForm.tsx
src/pages/find/IdTab.tsx
src/pages/signin/SignInForm.tsx
src/pages/signup/EmailRow.tsx
src/pages/signup/EmailVerifyRow.tsx
src/pages/signup/PasswordRow.tsx
src/pages/signup/SignUpForm.tsx
src/pages/signup/StudentNumberRow.tsx

로그인/회원가입 1차 QA 개선사항 반영
1차 QA 후 로그인/회원가입 화면에서 필요한 개선사항을 반영한다.
- 공통 컴포넌트
- 공통 Spinner 컴포넌트 정의
- 로그인 오류 문구 개선: 404... -> 서버 에러 메세지로 변경
- 회원가입 시 비밀번호 규칙을 사전에 확인할 수 있도록 Input의 placeholder에 추가
- 모바일 환경에서 학번 입력 시 숫자 키패드가 뜰 수 있도록 inputMode decimal 설정
- (피드백: 아이디 찾기 토스트 메시지가 너무 느림)
- 네트워크 응답 속도가 느린 경우 + 실패 시 tanstack query의 retry로 인해 toast가 느리다고 느껴질 수 있음 -> 로딩 스피너 추가하여 해결
- 이메일 인증 버튼 클릭 시 Spinner 처리
- 이메일 인증 버튼 클릭 시 버튼 내부 텍스트 변경에 따른 버튼 크기 변경 -> min width 적용하여 크기 변경이 없도록 수정
- 피드백 : 이메일 도메인이 @pusan.ac.kr 고정이라면 텍스트 필드에서 제외
- UI디자인이 나와있지 않고, Input 우측에 @pusan.ac.kr 텍스트를 배치하면 안이쁠 것 같음
- Input 내에서 @pusan.ac.kr을 붙이는 로직을 추가할 수는 있다. (꼭 필요한지는 의문)

Design: 로그인/회원가입 1차 QA 개선사항 반영

---

src/layout/Header.tsx

Header mobile 화면 높이 수정
Header mobile 화면 높이 수정
헤더 css 수정
lg:h-header md:h-header xs:h-8 sm:h-16

design: Header mobile 화면 높이 수정

---

src/pages/main/LeaderMessage.tsx
src/pages/main/LeaderSection.tsx
src/pages/main/MainPage.tsx
src/pages/main/TeamCard.tsx
src/pages/main/TeamCardSkeleton.tsx

6/26 회의 후 개선사항 적용 
반응형으로 수정 
- 팀장 메시지 에디터 버튼 반응형 구현 (RoundedButton -> button 으로 변경)
- 팀장 메시지 ellipsis 처리 
-  메인페이지 접근 시 scrollToTop 적용 (라우터 true -> useLocation 추가)
-  카드 내부 텍스트 반응형 구현 (최소 사이즈까지 축소->ellipsis)
- 좋아요 버튼 오른쪽 상단 배치 (isLiked==False인 경우 출력x)
- 팀카드 스켈레톤 반응형 수정

design: 메인페이지 반응형 수정

---

src/pages/project-viewer/CarouselSection.tsx
src/pages/project-viewer/LikeSection.tsx
src/pages/project-viewer/ProjectViewerPage.tsx

- 좋아요 정보를 반영하는 `LikeSection.tsx`에 `invalidate query`를 적용하여 최신 정보 반영하도록 함
- 기존 initLiked 제거없이 뷰어 페이지로부터 props 받음 (버그 수정)
- Youtube URL의 embed URL이 유효하지 않을 경우 캐러셀에 띄우지 않음

Fix: invalidate query 적용

---

src/apis/contests.ts
src/layout/Header.tsx
src/layout/HeaderMenu.tsx
src/main.tsx
src/mocks/data/contests.ts
src/mocks/handlers/contests.ts
src/mocks/handlers/index.ts
src/types/DTO/contestsDto.ts
src/types/DTO/index.ts

헤더 히스토리 드롭다운 구현
헤더 히스토리 드롭다운 구현
- /contests API msw 핸들러 정의 및 msw 활성화
- HeaderMenu 컴포넌트 구현
- Hover 시 드롭다운 open
- '히스토리', 드롭다운 아이템 클릭 시 /contest 또는 /contest/{contestId}로 라우팅
- '히스토리'클릭 시 라우팅 처리하였기 때문에 Api 예외처리는 하지 않음
- 헤더 메뉴 표현을 위해 Header 로고 크기 반응형 처리 및 md breakpoint에서 '관리자 페이지' 텍스트 제거
[PC]

Feat: 헤더 히스토리 드롭다운 구현

---

src/components/RoundedButton.tsx
src/pages/find/FindEmailForm.tsx
src/pages/find/FindEmailResult.tsx
src/pages/find/PasswordTab.tsx
src/pages/main/LeaderMessage.tsx
src/pages/main/LeaderSection.tsx

팀장 메세지 반응형 스타일링 적용
팀장 메세지에 반응형 스타일링을 적용한다.
- LeaderSection, LeaderMessage
- 반응형 텍스트 크기, 버튼 크기 적용
- RoundedButton
- min width 제거 후 RoundedButton 사용 컴포넌트에서 min-w 관리하도록 변경
|전체 화면|모바일|
|---|---|
|<img width="1656" alt="image" src="https://github.com/user-attachments/assets/5c0fb574-c18c-4688-9f3b-45830356e948" />|<img width="383" alt="image" src="https://github.com/user-attachments/assets/99d4f2b4-7c72-4eeb-b380-58e2415559c0" />|

Design: 팀장 메세지 반응형 스타일링 적용

---

src/layout/HeaderMenu.tsx

fix: 모바일뷰에서 HeaderMenu가 적절히 동작할 수 있도록 수정
fix: 모바일뷰에서 HeaderMenu가 적절히 동작할 수 있도록 수정
- '히스토리' 클릭 시 /constest로 이동하지 않고 드롭다운의 상태만 변경하도록 수정

fix: 모바일뷰에서 HeaderMenu가 적절히 동작할 수 있도록 수정

---

src/apis/projectEditor.ts
src/apis/projectViewer.ts
src/components/Button.tsx
src/hooks/useContestAdmin.ts
src/hooks/useId.ts
src/pages/admin/ContestAdminTab.tsx
src/pages/project-editor/AdminInputSection/AdminInputSection.tsx
src/pages/project-editor/AdminInputSection/ContestMenu.tsx
src/pages/project-editor/AdminInputSection/MembersInput.tsx
src/pages/project-editor/ImageUploaderSection.tsx
src/pages/project-editor/ProjectCreatorPage.tsx
src/pages/project-editor/ProjectEditorPage.tsx
src/pages/project-viewer/CarouselSection.tsx
src/pages/project-viewer/IntroSection.tsx
src/pages/project-viewer/ProjectViewerPage.tsx
src/route/AdminTabs.tsx
src/types/DTO/projectViewerDto.ts

- 정상적인 백엔드 API 연결 후 `ProjectEditorPage.tsx`를 재활용하여 아래 문제는 해결되었습니다.
> 우선 프로젝트가 POST 되는 것만 테스트하기 위해 `ProjectCreatorPage.tsx`를 구현하였습니다.
> POST 후 teamId가 발급되고 이전 대회 리스트에도 뜨는 것을 확인했으나 뷰어 페이지에서 렌더링이 안돼서 이 부분은 확인 후 수정하겠습니다.
- 서버에서 webp로 변환 중인 이미지를 `ERROR_409`로 분류하여, 안내 메시지가 뜨도록 구현하였습니다.
- 관리자 페이지에서 수정 또는 삭제 시 아래로 리다이렉트 또는 토스트 메시지가 뜨도록 설계하였습니다.
- 현재 진행 중인 대회(제6회PNU창의융합해커톤)의 프로젝트들을 수정 또는 삭제하는 경우: 토스트 메시지를 띄웁니다.
- 이전 대회의 프로젝트들을 수정하는 경우: 팀장 수정 페이지에서 보았던 것처럼 수정 페이지로 리다이렉트됩니다.
- 관리자 페이지에서 프로젝트 생성이 가능하도록 구현하였습니다. 시나리오는 다음과 같습니다.
- `프로젝트 생성하기` 버튼 클릭 시 POST API 호출하여 `teamId`를 response로 받는다.
- `response.teamId`를 수정 페이지의 URI 파라미터로 붙여 리다이렉트한다.
- 수정 페이지에서 프로젝트 편집을 한다.
- 관리자의 기능 추가 구현을 위함입니다.
- 기존 컴포넌트 활용을 위해 `isLeader`, `isAdmin` (useAuth), `isLeaderOfThisTeam`을 활용하였습니다.
- `useContestAdmin` 훅에 …

Feat: 프로젝트 생성 컴포넌트

---

src/apis/projectEditor.ts
src/pages/project-editor/ProjectEditorPage.tsx

- 팀원 추가 API 호출 시 DTO 사용 오류로 `권한이 없습니다.` 메시지 뜨던 오류를 해결하였습니다.
- API 호출 인자를 `teamMemberName: string`에서 `body: TeamMemberCreateRequestDto`로 변경하였습니다.
https://github.com/user-attachments/assets/46722834-7ff6-4541-a0c6-7bc9fe2d0689

Fix: 팀원 추가 API 호출 시 DTO 사용

---

src/pages/admin/NoticeManageTab/ManageNoticeListTab.tsx
src/pages/admin/NoticeManageTab/NoticeCreateTab.tsx
src/pages/admin/NoticeManageTab/NoticeEditTab.tsx

공지사항 작성 완료 시 invalidateQuery 처리
공지사항 생성, 수정, 삭제 시 즉시 확인할 수 있도록 invalidateQuery 처리
- NoticeCreateTab에서 mutate onSuccess시 invalidateQuery로직 추가

fix: 공지사항 작성 완료 시 invalidateQuery 처리

---

src/components/Button.tsx
src/pages/admin/AdminPage.tsx
src/pages/admin/ContestAdminTab.tsx
src/pages/admin/NoticeManageTab/ManageNoticeListTab.tsx

관리자 대회관리 탭 아래 히스토리 검색 시 Menu 닫히게 수정
클릭했는데 계속 Menu가 안닫혀서 isOpen(false)로 닫히게 수정
button 에 간단히 isOpen 을 false로 수정했습니다.
`onClick={() => {
onContestChange(contest.contestName, contest.contestId);
setIsOpen(false);
}}`

fix: 히스토리 클릭 시 Menu 닫히게 수정

---

src/components/Table.tsx

Table 컴포넌트 헤드 왼쪽 정렬
테이블 텍스트 정렬 일관성을 위해 text 왼쪽 정렬
Table 컴포넌트 thead text-left로 수정 했습니다.
편집은 중앙정렬이 더 괜찮아보여서 나뒀습니다.

design: 테이블 헤더 편집제외 왼쪽 정렬

---

src/pages/main/NoticeList.tsx
src/pages/main/TeamCard.tsx
src/pages/notice/NoticeDetail.tsx

전체회의 전 QA 중 발견한 버그 수정 
- 메인페이지 프로젝트 카드 hover 일치 처리
- 공지사항 상세 페이지 반응형 텍스트 크기 변경 구현
- 메인페이지 공지사항 리스트에서 제목부분만 link 됨 문제 -> 링크 영역 확장 
- 프로젝트 카드 컴포넌트에서 overflow-hidden 중복 처리되어 있어 해당 버그 발생 -> 중복 없앰
- 공지사항 상세 페이지의 텍스트 세 부분 clamp 처리
- 공지사항 메인페이지 hover 영역과 link 영역 일치시킴

fix: 프로젝트 카드 hover 처리 및 공지사항 상세 페이지 반응형 구현 등등

---

src/pages/admin/NoticeManageTab/ManageNoticeListTab.tsx

admin 공지사항 목록 편집일시 크기 늘림
admin 공지사항 목록 편집일시 크기 늘림
- ManageNoticeListTab내 Table row의 width 조정
- 공지사항 제목 칸이 작아지는 문제가 있지만 추후 테이블 라이브러리 적용 후 수정 예정

design: admin 공지사항 목록 편집일시 크기 늘림

---

src/pages/project-viewer/LikeSection.tsx
src/pages/project-viewer/ProjectViewerPage.tsx

현재 진행중이지 않은 대회 프로젝트에서 좋아요 클릭 시 히스토리에 반영되지 않는 문제 해결
현재 진행중이지 않은 대회 프로젝트에서 좋아요 클릭 시 히스토리에 반영되지 않는 문제 해결
- LikeSection 컴포넌트에서 invalidateQuery 로직 추가
- 현재 contestId가 무엇인지 확인할 방법이 없어, 이전 대회의 프로젝트에 좋아요를 눌러도 메인 페이지에서 사용되는 현재 진행중 api에 대해 invalidate query하도록 함

fix: 현재 진행중이지 않은 대회 프로젝트에서 좋아요 클릭 시 히스토리에 반영되지 않는 문제 해결

---

src/layout/Header.tsx

Header 로고 내 글자에 맞춰 세로 정렬;;
SW교육센터에서 요구하여 로고 내 글자에 맞춰 header 내 컨텐츠 세로 위치 조절
- Header 컴포넌트 내 CSS속성 변경

design: Header 로고 내 글자에 맞춰 세로 정렬

---

src/pages/project-editor/AdminEditSection/AdminEditSection.tsx
src/pages/project-editor/AdminEditSection/ContestMenu.tsx
src/pages/project-editor/AdminEditSection/MembersInput.tsx
src/pages/project-editor/ImageUploaderSection.tsx
src/pages/project-editor/OverviewInput.tsx
src/pages/project-editor/ProjectEditorPage.tsx
src/pages/project-editor/UrlInput.tsx
src/pages/project-viewer/CommentSection/Comment.tsx
src/pages/project-viewer/CommentSection/CommentFormSection.tsx

- 팀원 수정 플로우를 재구성 하고 UI를 개선함
- 중복 검사 대상에 팀장 이름도 포함
- 사용자 입장에게 혼란스럽지 않은 수정 기능을 제공하기 위함
- 6개의 고정 칸을 두고 입력필드/추가/제거를 함께하여 사용 방식이 다소 복잡하다는 피드백을 수렴
- 입력 필드를 하나만 두는 것으로 하여 팀원이 추가될 때마다 아래 또는 우측에 배치되도록 함
- 명시적인 입력 필드를 제공함으로써 혼란이 없도록 함
- 아이콘이었던 삭제/추가 버튼을 `삭제`, `추가` 텍스트 버튼으로 변경 
- 참고: column 2개, sm: column 1개로 구현하였습니다.

Style: 팀원 수정 플로우 재구성 및 UI 개선

---

package-lock.json
package.json
src/components/Table.tsx
src/pages/admin/ContestsTab/ContestAdminTab.tsx
src/pages/admin/NoticeManageTab/ManageNoticeListTab.tsx
src/pages/admin/ProjectSubmissionTable.tsx

기존 테이블 컴포넌트에서 tanstack react-table을 추가해서 만들었습니다.
* 좌우 스크롤
* 공지사항 클릭 시 이동하기 위해 (Link 태그)
1. npm 으로 react-table 설치
2. react-table로 수정
3. 공지사항 Link 태그로 수정
4. 대회별 프로젝트 목록과 select 버튼이 모바일에서 깨짐 수정
* 좌우 스크롤
* 모바일에서 UI

Feat: Tanstack Table로 수정 / 모바일 UI 수정

---

src/pages/admin/NoticeManageTab/ManageNoticeListTab.tsx
src/pages/project-editor/AdminEditSection/AdminEditSection.tsx
src/pages/project-editor/AdminEditSection/ContestMenu.tsx
src/pages/project-editor/AdminEditSection/MembersInput.tsx
src/pages/project-editor/ImageUploaderSection.tsx
src/pages/project-editor/IntroSection.tsx
src/pages/project-editor/OverviewInput.tsx
src/pages/project-editor/ProjectEditorPage.tsx
src/pages/project-editor/UrlInput.tsx
src/pages/project-viewer/CarouselSection.tsx
src/pages/project-viewer/CommentSection/CommentFormSection.tsx
src/pages/project-viewer/CommentSection/CommentSection.tsx
src/pages/project-viewer/DetailSection.tsx
src/pages/project-viewer/IntroSection.tsx
src/pages/project-viewer/LikeSection.tsx
src/pages/project-viewer/MediaSection/GithubCard.tsx
src/pages/project-viewer/ProjectViewerPage.tsx
src/pages/project-viewer/ViewerSkeleton.tsx
src/utils/media.ts

- `깃헙 카드` -> `url 버튼`으로 대체했었던 깃헙 링크 진입점을 다시 `깃헙 카드`로 구현함
- 화면 너비에 따른 css를 개선함
- 사용자들의 편리한 접속을 위함
- 뷰어 페이지와 에디터 페이지에, 너비에 따라 패딩과 최소 너비 속성을 부여
- 그 외 폰트 사이즈 반응형으로 수정
- 깃헙과 유튜브의 url 버튼을 없애고 `프로젝트 바로가기` 버튼만 남김
- 팀원 한명 당 글자 수를 20자로 제한하였습니다.
- url 입력 필드에 있던 '필수', '선택' placeholder의 css를 개선
- 이미지 업로더 가이드를 모바일에서도 볼 수 있도록 `active` 속성 추가
- 사파리 브라우저 확인이 필요합니다!
- GitHub embed card
- IntroSection responsive UI
- 프로젝트명 또는 팀명이 길어질 경우를 고려하여 md를 기준으로 `flex-row`, `flex-col`을 적용
- Url textfield placeholder css improvement

Feat: GitHub embed card 구현

---

src/pages/main/NoticeList.tsx
src/pages/notice/NoticeDetail.tsx

변경된 공지사항 api 상세페이지에 적용 
작성일(createdAt)과 수정일(updatedAt)을 공지사항 상세페이지에 따로 띄우기 
- NoticeDetail 에서 updatedAt과 createdAt을 'YYYY.MM.DD' 형식으로 출력
- 메인페이지 공지사항 리스트 날짜 출력 형식 변경

add: 작성일, 수정일 공지사항 상세페이지 적용 

---

src/apis/teams.ts
src/pages/main/TeamCard.tsx
src/types/DTO/teams/thumbnailResponseDto.ts

이미지 변환 202 상태 반영 코드 추가 및 URL 문자열 구성 방식 변경 
- 추가된 202 상태 -> 기본 이미지 반영
- 배포된 서버에서 가는 썸네일 api 주소가 로컬의 경우와 다름 (URL 문자열 방식 수정해봄)
- teams api 파일에 썸네일 api 추가 및 기존 직접 문자열 구성 방식 변경

fix: 썸네일 api 변경 

---

src/apis/projectEditor.ts
src/pages/project-editor/ImageUploaderSection.tsx
src/pages/project-editor/ProjectEditorPage.tsx

- 이미지 압축 중인 상태에서 삭제가 불가하다는 토스트 메시지를 띄움
- 기존에는 압축 중인 상태에서도 삭제가 가능했으나, 삭제가 불가능해짐에 따라 구현
https://github.com/user-attachments/assets/65873777-19d4-47e3-b2c1-2a2ef5c7d5ef

Feat: 이미지 압축 시 삭제 불가

---

src/pages/project-viewer/LikeSection.tsx

좋아요 남용 경고 툴팁 구현
다수의 계정으로 좋아요 남용 시 제제될 수 있음을 안내하는 경고 툴팁 구현
- LikeSection에 LikeAbuseToolTip 컴포넌트 추가
- 로컬 스토리지에 LikeAbuseToolTip을 확인 한 경우 계정의 userId를 저장하고, 이를 판단하여 툴팁 여부 출력

feat: 좋아요 남용 경고 툴팁 구현

---

src/components/AwardTag.tsx
src/components/ui/input.tsx
src/hooks/useAuth.ts
src/pages/admin/ContestsTab/AwardSet/AwardColorSelect.tsx
src/pages/admin/ContestsTab/AwardSet/AwardSetSection.tsx
src/pages/admin/ContestsTab/AwardSet/SortableTable.tsx
src/pages/admin/ContestsTab/AwardSet/TeamSelect.tsx
src/pages/project-editor/AdminEditSection/AdminEditSection.tsx
src/pages/project-editor/ImageUploaderSection.tsx
src/pages/project-editor/IntroSection.tsx
src/pages/project-editor/ProjectEditorPage.tsx
src/pages/project-viewer/CarouselSection.tsx
src/pages/project-viewer/DetailSection.tsx
src/pages/project-viewer/IntroSection.tsx
src/pages/project-viewer/ProjectViewerPage.tsx
src/types/DTO/projectEditorDto.ts
src/types/DTO/projectViewerDto.ts
src/types/MemberType.ts

- 팀장에게만 있던 프로젝트 편집 권한을 팀원에게도 부여합니다.
- 졸업과제 포스터 규격(2:3)에 맞는 이미지를 보여줍니다.
- 효율적인 졸업과제 프로젝트 관리를 위해서입니다.

feat: 팀원 편집 권한 추가 및 포스터 이미지 규격 지원

---

src/pages/signin/SignInOptions.tsx

팀원 권한 추가로 인한 회원가입 툴팁 수정
팀원 권한 추가로 인한 회원가입 툴팁 수정
- 팀장 뿐만 아니라 팀원도 소셜로그인이 아닌 서비스 회원가입이 필요
- 이를 안내하기 위한 툴팁 구현 및 기존 안내 문구 수정
- 툴팁 문구 변경
- "팀장 또는 팀원이신가요? 소셜로그인 대신 직접 회원가입 해주세요"

design: 로그인 툴팁 문구 변경

---

src/constants/contest.ts
src/pages/project-editor/AdminEditSection/ContestMenu.tsx
src/pages/project-editor/ProjectEditorPage.tsx

현재 진행중인 대회 id를 1로 하드코딩하던 코드 공통 상수로 변경
이전 변경에서 미흡한 코드 변경 문제를 해결
- contestId를 1로 하드코딩중인 코드 재확인 및 수정
- @redzzzi 지연님 담당 부분이라 크로스체크 필요할 것 같습니다. 제가 변경한 부분 적용해도 되는지 검토 부탁드립니다.

fix: 현재 진행중인 대회 id를 1로 하드코딩하던 코드 공통 상수로 변경

---

src/pages/project-viewer/CarouselSection.tsx

캐러셀에서 일부 이미지가 잘려 보이는 문제 수정
테크위크 프로젝트 포스터 이미지 표현을 위한 캐러셀 수정 이후 이전 대회들의 이미지가 잘려 보이는 문제를 수정하기 위함
- CarouselSection 컴포넌트의 css 속성을 조절하여 너비는 모든 이미지가 동일하고, 고정된 너비에 따라 높이가 결정되도록 수정
- 컴포넌트 구조가 복잡해 최소한의 수정으로 문제가 해결될 수 있도록 진행했습니다. 중첩된 태그들 간의 CSS 속성을 깊이 고려하지 못한 수정이 있을 수 있습니다..!
|변경 전|변경 후|
|---|---|
|<img width="1440" height="998" alt="image" src="https://github.com/user-attachments/assets/eaa2574c-a3f1-4bb7-9cde-40e620a17ea5" />|<img width="1440" height="969" alt="image" src="https://github.com/user-attachments/assets/5bacdb59-fb2b-4191-8a9c-0927d132a1c9" />|

fix: 캐러셀에서 일부 이미지가 잘려 보이는 문제 수정
